Revert "Remove --ignore-installed when installing guild dist"
This reverts commit 80a2fdaa360095eba97942d8411acd9c79335639.

We def need `--ignore-installed`. Without it, this pip issue surfaces
and Guild isn't installed in the env.

The result is that imports fail in uat:

```
RuntimeError: guild.ipy requires pandas - install it first before
using this module (see
https://pandas.pydata.org/pandas-docs/stable/install.html for help)
```

This is because Guild doesn't run in the virtual env.